[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "gtk3",
  "libx11",
  "libxcomposite",
  "libxdamage",
  "libxext",
  "libxfixes",
  "libxrandr"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"
